version: '3.8'

services:
        nginx:
            container_name: cms_nginx
            build:
                context: .
                dockerfile: ./docker/nginx/Dockerfile
            ports:
                - 8000:80
            volumes:
                - ./cms:/var/www/html
                - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf        # Mount tệp cấu hình chính của Nginx
                - ./docker/nginx/conf.d:/etc/nginx/conf.d 
            restart: unless-stopped
            networks:
                - internal

        php-fpm:
            container_name: cms_php
            build:
                context: .
                dockerfile: ./docker/php/Dockerfile
            volumes:
                - ./cms:/var/www/html
            restart: unless-stopped
            networks:
                - internal
        db:
            container_name: cms_db
            image: mariadb:latest
            restart: unless-stopped
            environment:
                MYSQL_ROOT_PASSWORD: 'ngn@0x6e676e'
                MYSQL_USER: 'ngn'
                MYSQL_PASSWORD: 'ngn@0x6e676e'
                MYSQL_DATABASE: 'hydropkit'
            volumes:
                - ./db_cms:/var/lib/mysql
                - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d 
            networks:
                - internal
            

        phpmyadmin:
            image: phpmyadmin/phpmyadmin
            container_name: cms_pma

            networks:
                - internal
            environment:
                PMA_HOST: db
                PMA_PORT: 3306
                PMA_ARBITRARY: 1
            restart: always
            ports:
                - "9876:80"

networks:
    internal:
        driver: bridge